server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      force: true

spring:
  main:
    banner-mode: off
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.50.244:3306/db_reggie?allowPublicKeyRetrieval=true&serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  redis:
    host: 192.168.50.244
    port: 6379
    database: 0
  cache:
    redis:
      time-to-live: 1800000 #设置缓存过期时间 30min

mybatis-plus:
  global-config:
    banner: false
    db-config:
      id-type: assign_id
      # 逻辑删除
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

